kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: maven:3.8.6-jdk-8
  commands:
  - mvn clean package
  - wget https://raw.githubusercontent.com/HyperTNTClown/drone-webdav/master/push.sh
  - chmod +x push.sh
  - ./push.sh
  environment:
    PLUGIN_FILE: TimoCloud-Universal/target/TimoCloud.jar
    PLUGIN_BASE_URL:
      from_secret: webdav_baseurl
    PLUGIN_USERNAME:
      from_secret: webdav_username 
    PLUGIN_PASSWORD:
      from_secret: webdav_password
    PLUGIN_DESTINATION: $DRONE_REPO/$DRONE_BUILD_NUMBER/
    
